version: '3.3'
services:
    influx_integration:
        image: influx_integration
        build:
            context: ./influx_integration
        environment:
            - INFLUX_URL=http://influxdb:8086
            - INFLUX_TOKEN=T83eOo-vBhs9Vj137wTddvdLt_f3rr4WOTBPc3HpR2vb7w2JEg-Q6DTEKGGpEKFOXs6fWEcmTSUMN-rlE_6p7g==
            - INFLUX_ORG=myOrg
        depends_on:
            - "mosquitto"