version: '3.4'

services:
  influx:
    image: influx
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 main.py "]
    environment:
      - influx_url=http://influxdb:8086
      - token=VU6i3UKfqeCkw-f3fSKZU2svjk34wyb6gHoABMhemdhpO4IjCrwlVDvA9L5CyN3xUdGjJMyQs2jqBfOMdbl2HQ==
      - org=myOrg
    ports:
      - 5678:5678
  #   depends_on:
  #     - influxdb

    
  # influxdb:
  #   image: influxdb:2.0.9
  #   restart: unless-stopped
  #   ports:
  #     - 8086:8086
  #   volumes:
  #     - ./data/influxdb:/var/lib/influxdb2
  #   command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt
  #   environment:
  #     - INFLUXDB_ADMIN_USER=admin
  #     - INFLUXDB_ADMIN_PASSWORD=password
  #     - INFLUXDB_USER=influx
  #     - INFLUXDB_USER_PASSWORD=password
  #     - INFLUXD_QUERY_CONCURRENCY=20
  #     - INFLUXD_QUERY_QUEUE_SIZE=200
  #     - INFLUXD_SESSION_LENGTH=120
